In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv("production_analysis_dataset (1).csv")
df

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209

In [3]:
df.columns

Index(['production_id', 'product_category', 'factory', 'shift', 'supervisor',
       'units_produced', 'defective_units', 'production_time_hr',
       'machine_downtime_hr', 'energy_consumption_kwh', 'profit'],
      dtype='object')

# Q1. Find the total units produced by each product_category.

In [4]:
df.groupby("product_category")["units_produced"].sum().reset_index()

  product_category  units_produced
0       Automotive            9408
1      Electronics            7491
2        Furniture            7251

# Q2. Calculate the average profit for each factory.

In [5]:
df.groupby("factory")["profit"].mean().reset_index()

   factory        profit
0  Plant_A  18044.375000
1  Plant_B  16973.384615
2  Plant_C  18086.076923

# Q3. Find the total defective_units for each shift.

In [6]:
df.groupby("shift")["defective_units"].sum().reset_index()

     shift  defective_units
0  Evening              132
1  Morning              472
2    Night              471

# Q4. Calculate the average production_time_hr for each supervisor.

In [7]:
df.groupby("supervisor")["production_time_hr"].mean().reset_index()

  supervisor  production_time_hr
0         S1            7.801818
1         S2            7.450000
2         S3            7.882000
3         S4            7.956154

# Q5. Find the total energy_consumption_kwh for each factory and shift.

In [8]:
df.groupby([ "factory", "shift"])["energy_consumption_kwh"].mean().reset_index()

   factory    shift  energy_consumption_kwh
0  Plant_A  Evening             1110.000000
1  Plant_A  Morning             1114.400000
2  Plant_A    Night             1173.909091
3  Plant_B  Evening             1444.500000
4  Plant_B  Morning             1131.857143
5  Plant_B    Night             1245.250000
6  Plant_C  Evening             1107.000000
7  Plant_C  Morning             1126.400000
8  Plant_C    Night             1227.166667

# Q6. For each product_category, calculate:
total units_produced
average profit
maximum defective_units.

In [9]:
df.groupby("product_category").agg({"units_produced":["sum"],"profit":["mean"],"defective_units":["max"]})

                 units_produced        profit defective_units
                            sum          mean             max
product_category
Automotive                 9408  18374.722222              34
Electronics                7491  16945.750000              40
Furniture                  7251  17935.062500              39

# Q7. For each factory, calculate:
mean production_time_hr
median machine_downtime_hr.

In [10]:
df.groupby("factory").agg({"production_time_hr":["mean"],"machine_downtime_hr":["median"]})

        production_time_hr machine_downtime_hr
                      mean              median
factory
Plant_A           7.890000               0.945
Plant_B           7.579231               1.070
Plant_C           7.810769               0.850

# Q8. For each shift, compute:
minimum profit
maximum profit
average units_produced.

In [11]:
df.groupby("shift").agg({"profit":["min"],"profit":["max"],"units_produced":["mean"]})

        profit units_produced
           max           mean
shift
Evening  22302     524.857143
Morning  24358     482.090909
Night    24586     470.000000

# Q9. For each supervisor, calculate:
total units_produced
total defective_units.

In [12]:
df.groupby("supervisor").agg({"units_produced":["sum"],"defective_units":["sum"]})

           units_produced defective_units
                      sum             sum
supervisor
S1                   5231             209
S2                   6069             264
S3                   7418             273
S4                   5432             329

# Q10. Using apply(), calculate the defect rate for each row:
defect_rate=defective_units/units_produced

In [15]:
df.apply(lambda x:(x["defective_units"]/x["units_produced"])*100 if x["units_produced"]!=0 else 0.0,axis=1)

0      1.913876
1      5.315615
2      5.855856
3      4.641350
4      4.411765
5      4.508857
6      8.262108
7      1.365706
8      6.379585
9      4.356436
10     6.772908
11     5.016722
12     3.968254
13     0.857633
14     7.111111
15     1.967800
16     2.173913
17     7.843137
18    10.495627
19     2.581756
20     3.609023
21     2.168675
22     2.158273
23     9.535452
24     2.770781
25     9.063444
26     8.625337
27     5.763689
28     9.634551
29     4.485488
30     2.431611
31     2.686567
32     1.620746
33     4.976303
34     1.779935
35     3.370787
36     1.721440
37     5.239180
38     1.869159
39     8.638743
40     8.179959
41     1.716069
42     7.948718
43     3.440367
44     5.010438
45     2.036199
46     3.821656
47     5.252101
48     4.833837
49     6.584362
dtype: float64

# Q11. Using groupby().apply(), find the profit range (max − min) for each factory.

In [21]:
df.groupby("factory")["profit"].apply(lambda x: (x.max() - x.min(),x.max(),x.min()))

factory
Plant_A    (14199, 24586, 10387)
Plant_B    (14349, 24358, 10009)
Plant_C    (12745, 24577, 11832)
Name: profit, dtype: object

# Q12. Using groupby().apply(), find the row with maximum units_produced in each product_category.

In [25]:
df.groupby("product_category")["units_produced"].apply(lambda x: x.max()).reset_index()

  product_category  units_produced
0       Automotive             690
1      Electronics             666
2        Furniture             618

# Q13. Use apply() to create a new column efficiency_score:
efficiency=units_produced/production_time_hr

In [29]:
df["efficiency_score"]=df.apply(lambda x: x["units_produced"]/x["production_time_hr"],axis=1)
df

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,efficiency_score
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,95.288754
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,91.212121
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,85.824742
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,68.005739
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,53.363229
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834,75.455650
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664,47.885402
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010,79.111645
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713,87.569832
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358,75.373134
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197,72.438672
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348,78.787879
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304,42.567568
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302,68.266979
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349,64.562410
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317,61.361142
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009,84.975369
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923,39.059081
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547,38.324022
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470,79.589041
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177,86.363636
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641,55.259654
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423,45.227766
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440,59.275362
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735,58.468336
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073,38.133641
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260,52.624113
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166,49.571429
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673,41.232877
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054,51.285521
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579,39.878788
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586,39.273154
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183,79.510309
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491,54.876463
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170,91.964286
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021,56.978233
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577,68.562232
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263,52.827918
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722,63.126844
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832,46.813725
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974,70.461095
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168,84.788360
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818,59.360731
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067,49.209932
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387,53.459821
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346,47.021277
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349,34.392114
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311,60.947503
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253,101.689708
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209,72.429210

# Q14. Find how many times each product_category appears in the dataset.

# Q15. Count the number of records for each shift.

# Q16. Find the most frequent supervisor using value_counts().

# Q17. Sort the dataset by profit in descending order.

# Q18. Sort the dataset by:
•	product_category ascending
•	units_produced descending