In [1]:
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

In [2]:
with open('../Scrap/140 Essential Action Movies To Watch Now ｜ Rotten Tomatoes (5_28_2025 8：24：58 AM).html',
          'r',encoding='UTF-8') as f:
    html= f.read()

In [3]:
soup = BeautifulSoup(html,'html.parser')

In [21]:
box = soup.find_all('div',class_='row countdown-item')
len(box)

140

In [34]:
data = {'movename':[],'score':[],'img_url':[],'directer':[]}

In [32]:
box[0].find('div',class_='row countdown-item-details').find('div',class_='info director').find('a').text

'Peter Hyams'

In [35]:
for i in box:
    data['movename'].append(i.find('div',class_='col-sm-20 col-full-xs').find('a').text)
    data['score'].append(int(i.find('div',class_='col-sm-20 col-full-xs').find('span',class_='tMeterScore').text.split('%')[0]))
    data['img_url'].append(i.find('div',class_='col-sm-6 col-full-xs').find('img',class_='article_poster').get('src'))
    data['directer'].append(i.find('div',class_='row countdown-item-details').find('div',class_='info director').find('a').text)

In [36]:
df = pd.DataFrame(data)
df

,movename,score,img_url,directer
0,Running Scared,63,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",Peter Hyams
1,Equilibrium,40,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",Kurt Wimmer
2,Hero,94,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",Yimou Zhang
3,Road House,44,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",Rowdy Herrington
4,Unstoppable,87,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",Tony Scott
...,...,...,...,...
135,Hard-Boiled,92,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",John Woo
136,The Matrix,83,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",Lilly Wachowski
137,Terminator 2: Judgment Day,91,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",James Cameron
138,Die Hard,94,"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",John McTiernan
139,Mad Max: Fury Road,97,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",George Miller

In [37]:
with open('../Scrap/List of state and union territory capitals in India - Wikipedia (5_28_2025 8：46：50 AM).html','r',encoding='UTF-8') as f:
    html = f.read()

In [40]:
soup = BeautifulSoup(html,'html.parser')
table =soup.find('table',class_='wikitable sortable jquery-tablesorter')
len(table)

2

In [73]:
with open('../Scrap/Certified used Mercedes-Benz for sale (1).html','r',encoding='UTF-8') as f:
    html = f.read()

In [74]:

soup = BeautifulSoup(html,'html.parser')
box = soup.find_all('div',class_='vehicle-details')
len(box)

21

In [109]:
data = {'Name':[],'year':[],'mileage':[],'price':[],'rating':[],'reviews':[],'dealer_name':[]}

In [106]:
float(box[0].find('div',class_='vehicle-dealer').find('div','sds-rating').find('span',class_='sds-rating__link sds-button-link').text.split(' ')[0].replace('(',''))

130.0

In [110]:
for i in box:
    data['Name'].append(i.find('h2',class_='title').text[5:]) 
    data['year'].append(i.find('h2',class_='title').text[0:4])
    data['mileage'].append(i.find('div',class_='mileage').text.split(' ')[0].replace(',',''))
    data['price'].append(i.find('div',class_='price-section price-section-vehicle-card').find('span').text.replace('$','').replace(',',''))
    try:
        data['rating'].append(float(i.find('div',class_='vehicle-dealer').find('div','sds-rating').find('span').text))
    except:
        data['rating'].append(np.nan)
    try:
        data['reviews'].append(float(i.find('div',class_='vehicle-dealer').find('div','sds-rating').find('span',class_='sds-rating__link sds-button-link').text.split(' ')[0].replace('(','')))
    except:
        data['reviews'].append(np.nan)
    
    
    data['dealer_name'].append(i.find('div',class_='vehicle-dealer').find('div','dealer-name').text.strip())

In [111]:
df = pd.DataFrame(data)
df

,Name,year,mileage,price,rating,reviews,dealer_name
0,Mercedes-Benz CLA 250 Base 4MATIC,2020,28744,35995,4.4,130.0,Mercedes-Benz of Lynnwood
1,Mercedes-Benz AMG GT 53 Base,2019,25771,79995,4.0,117.0,International Autos
2,Mercedes-Benz AMG GLE 53 Base,2021,22374,80923,2.8,38.0,John Sisson Motors
3,Mercedes-Benz AMG CLA 45 Base 4MATIC,2022,10595,56633,NaN,NaN,Mercedes-Benz of Santa Rosa
4,Mercedes-Benz AMG GLE 53 Base,2021,33622,76995,4.7,152.0,Mercedes-Benz of Rochester
5,Mercedes-Benz E-Class E 450 4MATIC,2021,12477,76532,4.5,NaN,Benzel-Busch Motor Car
6,Mercedes-Benz AMG GLE 63 S-Model 4MATIC,2021,22383,102990,4.8,174.0,Mercedes-Benz of Lancaster
7,Mercedes-Benz S-Class S 560,2019,49332,54580,4.8,NaN,Mercedes-Benz of Ontario
8,Mercedes-Benz AMG GLE 53 Base,2021,37688,76715,2.8,38.0,John Sisson Motors
9,Mercedes-Benz GLA 250 Base,2021,19521,34999,4.6,264.0,Mercedes-Benz of Augusta
10,Mercedes-Benz AMG C 43 Base 4MATIC,2022,14420,62991,4.8,NaN,Mercedes-Benz of Chicago
11,Mercedes-Benz AMG C 43 Base 4MATIC,2018,34555,39999,4.4,NaN,Mercedes-Benz of South Orlando
12,Mercedes-Benz E-Class E 450 4MATIC,2021,16474,74998,4.8,226.0,Contemporary Motor Cars Inc.
13,Mercedes-Benz S-Class S 580 4MATIC,2021,10233,99822,4.5,NaN,Mercedes-Benz of Fort Washington
14,Mercedes-Benz GLE 450 AWD 4MATIC,2022,6800,73990,4.8,NaN,Mercedes-Benz of Chicago
15,Mercedes-Benz GLC 300 Base 4MATIC,2018,54467,29151,4.5,NaN,Mercedes-Benz of Fort Washington
16,Mercedes-Benz AMG GLA 35 Base,2022,8690,49736,4.5,NaN,Mercedes-Benz of Fort Washington
17,Mercedes-Benz GLB 250 Base,2022,8158,42000,4.1,NaN,Mercedes-Benz Of Tampa
18,Mercedes-Benz S-Class S 500 4MATIC,2022,8401,86986,4.5,NaN,Mercedes-Benz of Walnut Creek
19,Mercedes-Benz AMG S 63 Base 4MATIC,2020,24958,105997,4.8,NaN,Autobahn Motors
20,Mercedes-Benz GLC 300 Base 4MATIC,2021,49278,37280,4.2,292.0,Bergstrom Luxury on Victory Lane