In [1]:
import pandas as pd
import numpy as np
df=pd.DataFrame([[1,2,3,4],[1,2,3,4],[1,2,5,6],[3,2,5,7],[7,2,5,6]])
df

   0  1  2  3
0  1  2  3  4
1  1  2  3  4
2  1  2  5  6
3  3  2  5  7
4  7  2  5  6

In [8]:
df.duplicated(subset=[2,3])

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [5]:
df.drop_duplicates() #keep = first - default

   0  1  2  3
0  1  2  3  4
2  1  2  5  6
3  3  2  5  7
4  7  2  5  6

In [7]:
df.drop_duplicates(keep='last')

   0  1  2  3
1  1  2  3  4
2  1  2  5  6
3  3  2  5  7
4  7  2  5  6

In [9]:
df.drop_duplicates(subset=[0],keep='last')

   0  1  2  3
2  1  2  5  6
3  3  2  5  7
4  7  2  5  6

In [10]:
df.drop_duplicates(subset=[0,2],keep='last')

   0  1  2  3
1  1  2  3  4
2  1  2  5  6
3  3  2  5  7
4  7  2  5  6

In [11]:
df.drop_duplicates(keep=False) #avoid to use this boolean keep = False

   0  1  2  3
2  1  2  5  6
3  3  2  5  7
4  7  2  5  6